Improve documentation for 0.4 release
php-task/docs pull request #2
Opened 2016-12-05 08:37 UTC by wachterjohannes

This PR improves documentation for 0.4 release

2016-12-05 09:53 UTC, danrot requested changes

2016-12-05 09:53 UTC, danrot commented on components.rst
> +The ``TaskScheduler`` stores tasks and schedules Executions. Foreach tasks there
`executions`

2016-12-05 09:53 UTC, danrot commented on components.rst
> +The ``TaskScheduler`` stores tasks and schedules Executions. Foreach tasks there
`foreach` is not one english word, must be `for each`

2016-12-05 09:53 UTC, danrot commented on components.rst
> +The ``TaskScheduler`` stores tasks and schedules Executions. Foreach tasks there
And it should be `task` instead of `tasks`

2016-12-05 09:53 UTC, danrot commented on components.rst
> +exists always on execution in the status ``planned``, ``running``. If the task
`exactly one execution`, or should that say something else?

2016-12-05 09:53 UTC, danrot commented on components.rst
> +execution will always generated for the next run time.
`For recurring tasks a new execution will be generated when the old one is completed.`?

2016-12-05 09:53 UTC, danrot commented on components.rst
> +- ``lastExecution``:
I would write another short explanation or remove the colons.

2016-12-05 10:09 UTC, wachterjohannes commented
@danrot fixed

2016-12-06 09:28 UTC, danrot approved these changes

2016-12-06 09:28 UTC, merged